version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./docker/app/.env
    depends_on:
      - db
    command: [ "/usr/local/bin/go-cloudnative-practice/wait-for-mysql.sh", "db", "usr/local/bin/go-cloudnative-practice/init.sh" ]

  db:
    build: ./docker/mariadb/
    environment:
      MYSQL_ROOT_PASSWORD: myapp_root_pass
      MYSQL_DATABASE: myapp_db
      MYSQL_USER: myapp_user
      MYSQL_PASSWORD: myapp_pass
    ports:
      - 3306:3306
    restart: always